### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by terrykeeton97** [Antelcat/ida_copilot#1]
Hi, could you possibly make an installation video? I'm new to reverse engineering and the installation is quite confusing with Python.

Thank you

**Comment by DearVa** [comment]
Sorry about my late reply. The installation of this plugin is quite simple: Just place the files into `plugin` folder. As for the IDAPython, it should be included in the IDA. If not, you can try another version of IDA or you can build and install it with this [Tutorial](https://youtu.be/dJx8cQEWosM?si=vM0MhSsOmy4QQO7U)
